config/routes.rb
Rails.application.routes.draw do
  get 'admin/home', to: "admin/base#home"
  namespace :admin do
    resources :users, only: [:index]
    resources :events
  end
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  root 'homepages#home'
  get 'wru/forum', to: 'forumpages#home' 
  resources :events , only: %i[index]do 
   resources :comments
  end
  resources :microposts do 
    resources :comments
  end
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  # belongs_to :commentable, polymorphic: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments
  default_scope -> { order(created_at: :desc) }
end

app/models/image.rb
class Image < ApplicationRecord

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  # has_many :comments, as: :commentable
  has_many :comments
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :microposts
  has_many :comments
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin/application'
  before_action :check_admin
  def home
    
  end 
  def check_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  def index
    @events = Event.all
  end
  def create
    @event = Event.new event_params
    if @event.save
      flash[:success] = 'Add successfully'
      redirect_to admin_events_path
    else
      flash[:danger] = 'Add fails'
      redirect_to admin_events_path
    end
  end

  # def show; end

  # def edit; end

  # def update
  #   if @category.update(category_params)
  #     flash[:success] = 'Update successfully'
  #     redirect_to admin_categories_path
  #   else
  #     flash[:danger] = 'Update fails'
  #     render :edit
  #   end
  # end

  # def destroy
  #   @category.destroy
  #   respond_to do |format|
  #     format.html { redirect_to admin_category_url, notice: 'Product was successfully destroyed.' }
  #     format.js
  #   end
  # end
  private 
  def event_params
    params.require(:event).permit :name, :content, :start_date, :end_date, :user_id
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
      permit_parameters_for_sign_up = [:name, :email,:password, :password_confirmation]
      permit_parameters_for_update = [:name,:password, :password_confirmation]
      devise_parameter_sanitizer.permit :sign_up, keys: permit_parameters_for_sign_up
      devise_parameter_sanitizer.permit :account_update, keys: permit_parameters_for_update
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if user_signed_in?
      @micropost = Micropost.find params[:micropost_id]
      @comment = @micropost.comments.build comment_params
      respond_to do |format|
        if @comment.save
          format.html{redirect_to wru_forum_path, notice: "create successful micropost"}
          format.js
        else
          format.html{redirect_to root_path, notice: "create fail micropost"}
          format.js
        end
      end
    else
      redirect_to root_path
    end
  end
  def update
  end
  def destroy
  end
  private 
  def comment_params
    params.require(:comment).permit :content, :user_id
  end
end

app/controllers/events_controller.rb
class EventsController < ForumpagesController
  def index 
    @events = Event.all
  end 
end

app/controllers/forumpages_controller.rb
class ForumpagesController < ApplicationController
    layout "layouts/forum/application"
    def home
        @micropost = current_user.microposts.build
        @list_microposts = Micropost.all
    end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
    def home
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    if user_signed_in?
      @micropost = current_user.microposts.build micropost_params
      respond_to do |format|
        if @micropost.save
          format.html{redirect_to wru_forum_path, notice: "create successful micropost"}
          format.js
        else
          format.html{redirect_to root_path, notice: "create fail micropost"}
          format.js
        end
      end
    else
      redirect_to root_path
    end
  end
  def update
  end
  def destroy
  end
  private 
  def micropost_params
    params.require(:micropost).permit :content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/events/index.html.erb
<div class="container">
  <h2>List Events</h2>      
  <!-- Button to Open the Modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myEvent">
  Create Event
</button>

<!-- The Modal -->
<div class="modal fade" id="myEvent">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Create Event</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <%= form_for :event, url: admin_events_path do |f| %>
        <div class="modal-body">
          <div class="form-group row">
            <label class="col-2 col-form-label">Name</label>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.text_field :name, class:"form-control", placeholder:"Write something..." %>
          </div>
          <div class="form-group row">
            <label class="col-2 col-form-label">Content</label>
            <%= f.text_field :content, class:"form-control", placeholder:"Write something..." %>
          </div>
          <div class="form-group row">
            <label for="example-datetime-local-input" class="col-2 col-form-label">Start</label>
            <div class="col-10">
              <%=f.datetime_field :start_date, class:"form-control", id:"example-datetime-local-input"%>
            </div>
          </div>
          <div class="form-group row">
            <label for="example-datetime-local-input" class="col-2 col-form-label">End</label>
            <div class="col-10">
              <%=f.datetime_field :end_date, class:"form-control", id:"example-datetime-local-input"%>
            </div>
          </div>      
        </div>
      <!-- Modal footer -->
        <div class="modal-footer">
              <%=f.submit "Create", class:"btn btn-primary", style:"width:100%"%>
        </div>
      <% end %>
    </div>
  </div>
</div>   
  <table id="listEvents" class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Content</th>
        <th>Time Start</th>
        <th>Time End</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each_with_index do |event, index|%>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= event.name%></td>
          <td><%= event.content%></td>
          <td><%= event.start_date%></td>
          <td><%= event.end_date%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script>
  $(document).ready( function () {
    $('#listEvents').DataTable();
} );
</script>

app/views/admin/users/index.html.erb
<div class="container">
  <h2>List Users</h2>         
  <table id="listUsers" class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Brith</th>
        <th>Gender</th>
        <th>Admin</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user, index|%>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= user.name%></td>
          <td><%= user.email%></td>
          <td><%= user.birth%></td>
          <td><%= user.gender%></td>
          <td><%=user.admin%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script>
  $(document).ready( function () {
    $('#listUsers').DataTable();
} );
</script>

app/views/comments/create.js.erb
$(".listItem").append("<%= j render 'forumpages/comment' , comment: @comment %>")

app/views/events/index.html.erb
<div class="container">
  <div class="listItemContent">
          <% @events.each do |event| %>
            <div class="itemContent publicBackground">
            <div class="contentMicropostOrEvent">
              <div class="contentDetail">
                <div class="textContent">
                  <div class="informationContent">
                    <i class='fas fa-user-edit'></i>
                    <b><%= event.user.name %></b>
                    <div>
                      <span><%= event.created_at.to_date%></span>
                    </div>
                  </div>
                  <span><%= event.content%></span>
                  <ul>
                    <li><b>Start time:</b> <%= event.start_date.to_datetime%></li>
                    <li><b>End time:</b> <%= event.end_date.to_datetime%></li>
                  </ul>
                </div>
                <div class="listImage">

                </div>
              </div>
              <div class="liveLikeAndQuantity">
                <div class="quantityLikeComment">
                  <div class="row">
                    <div class="col-md-5">
                      5 Like
                    </div>
                    <div class="col-md-7">
                      <%= event.comments.count%> Comments
                    </div>
                  </div>
                </div>
                <div class="functionCommentLike">
                  <div class="row">
                    <div class="col-md-6">
                      <i class="far fa-thumbs-up"></i>Like
                    </div>
                    <div class="col-md-6">
                      <i class="far fa-comment-alt"></i>Comment
                    </div>
                  </div>
                </div>
                <%= form_for :comment, url: event_comments_path(event), remote: true do |f| %>
                  <div class="postComment">
                    <div class="form-group" style="margin-top: 5px;">
                      <div class="row">
                        <div class="col-md-10">
                          <%= f.text_field :content, class:"form-control", placeholder:"Write something..." %>
                          <%= f.hidden_field :user_id, :value => current_user.id %>
                        </div>
                        <div class="col-md-2">
                          <%= f.submit "Post", class:"btn btn-primary"%>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <div class="listComment">
                  <% event.comments.each do |comment| %>
                    <div class="listItem">
                      <div class="informationUser">
                        <b><%= comment.user.name%></b>
                      </div>
                      <div class="commentItem">
                        <span><%= comment.content%></span>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
      </div>
</div>

app/views/forumpages/_comment.html.erb
<div class="listItem">
  <div class="informationUser">
    <b><%= comment.user.name%></b>
  </div>
  <div class="commentItem">
    <span><%= comment.content%></span>
  </div>
</div>

app/views/forumpages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="GroupInlineComposer">
        <div class="EnterComment publicBackground">
          <div class="row mainFunction">
            <div class="col-md-3">
              <div class="iconUser">
                <i class='fas fa-user-circle' style='font-size:38px'></i><b>ABCSS</b>
              </div>
            </div>
            <div class="col-md-9">
              <div class="postComment">
                <button type="button" class="btn" style="width: 100%; background-color: gainsboro;" data-toggle="modal" data-target="#createPost">
                  What's on your mind ?
                </button>
                <div class="modal fade" id="createPost">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title" style="text-aline:center">Create Post</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>
                      <!-- Modal body -->
                    <%= form_for @micropost, method: :post do |f| %>
                      <div class="modal-body">
                        <i class='fas fa-user-circle' style='font-size:24px'></i><b>Current user</b>
                        <div class="createMicropost" style='margin-top: 1em'>
                          
                            <div class="form-group">
                              <%= f.text_field :content, class:"form-control", placeholder:"Write something..." %>
                            </div>
                            <div class="row uploadFile" style="width: 100%;">
                            <div class="col-md-6">
                              <h6>Add to your photo</h6>
                            </div>
                            <div class="col-md-6">
                              <ul class="listChosse">
                                <li><a href="#"><i class="fas fa-video"></i></a></li>
                                <li><a href="#"><i class="fas fa-images"></i></a></li>
                                <li><a href="#"><i class="fas fa-user-friends"></i></a></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <%= f.submit 'Post', class:"btn btn-primary createPost", style:"width:31em"%>
                      </div>
                    <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row NoFunction">
            <div class="col-md-4"><button type="button" class="btn btn-outline-light text-dark">Room</button></div>
            <div class="col-md-4"><button type="button" class="btn btn-outline-light text-dark">Image/Video</button></div>
            <div class="col-md-4"><button type="button" class="btn btn-outline-light text-dark">Tag People</button></div>
          </div>
        </div>
        <div class="listItemContent">
          <% @list_microposts.each do |micropost| %>
            <div class="itemContent publicBackground">
            <div class="contentMicropostOrEvent">
              <div class="contentDetail">
                <div class="textContent">
                  <div class="informationContent">
                    <i class='fas fa-user-edit'></i>
                    <b><%= micropost.user.name %></b>
                    <div>
                      <span><%= micropost.created_at.to_date%></span>
                    </div>
                  </div>
                  <span><%= micropost.content%></span>
                </div>
                <div class="listImage">

                </div>
              </div>
              <div class="liveLikeAndQuantity">
                <div class="quantityLikeComment">
                  <div class="row">
                    <div class="col-md-5">
                      5 Like
                    </div>
                    <div class="col-md-7">
                      <%= micropost.comments.count%> Comments
                    </div>
                  </div>
                </div>
                <div class="functionCommentLike">
                  <div class="row">
                    <div class="col-md-6">
                      <i class="far fa-thumbs-up"></i>Like
                    </div>
                    <div class="col-md-6">
                      <i class="far fa-comment-alt"></i>Comment
                    </div>
                  </div>
                </div>
                <%= form_for :comment, url: micropost_comments_path(micropost), remote: true do |f| %>
                  <div class="postComment">
                    <div class="form-group" style="margin-top: 5px;">
                      <div class="row">
                        <div class="col-md-10">
                          <%= f.text_field :content, class:"form-control", placeholder:"Write something..." %>
                          <%= f.hidden_field :user_id, :value => current_user.id %>
                        </div>
                        <div class="col-md-2">
                          <%= f.submit "Post", class:"btn btn-primary"%>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <div class="listComment">
                  <% micropost.comments.each do |comment| %>
                    <%= render  "comment", comment: comment %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="aboutThisForum publicBackground">
        <h5 class="marginForpage">About</h5>
        <div class="row marginForpage">
          <div class="col-md-2">
            <i class='fas fa-lock-open'></i>
          </div>
          <div class="col-md-10">
            <div class="correspondingContetn">
              <h6>Public</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  // $(document).ready(function(){
  //   $(".createPost").click(function(){
  //     $.ajax({ 
  //       type: "post",
  //       url: 
  //     }});
  //   });
  // });
</script>

app/views/homepages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-xs-12">
      <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-interval="10000">
            <img src="https://previews.123rf.com/images/mathier/mathier1905/mathier190500001/134557215-no-thumbnail-images-placeholder-for-forums-blogs-and-websites.jpg" class="d-block w-100" alt="..." style="max-height: 30em;">
          </div>
          <div class="carousel-item" data-interval="2000">
            <img src="https://previews.123rf.com/images/mathier/mathier1905/mathier190500001/134557215-no-thumbnail-images-placeholder-for-forums-blogs-and-websites.jpg" class="d-block w-100" alt="..." style="max-height: 30em;">
          </div>
          <div class="carousel-item">
            <img src="https://previews.123rf.com/images/mathier/mathier1905/mathier190500001/134557215-no-thumbnail-images-placeholder-for-forums-blogs-and-websites.jpg" class="d-block w-100" alt="..." style="max-height: 30em;">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>
<div class="listStatistical">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-4">
        <div clas="statisticalItem">
          <div class="member">
            <h2 class="counter">1000</h2>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div clas="statisticalItem">
          <div class="event">
            <h2 class="counter">1000</h2>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div clas="statisticalItem">
          <div class="document">
            <h2 class="counter">1000</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="listEvent">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="sideBarRight"></div>
      </div>
      <div class="col-md-4">
        <div class="sideBarLeft"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-xs-12">
      <div class="topHeader">
        <ul class="nav justify-content-center">
          <% unless signed_in? %>
            <li class="nav-item">
              <%= link_to  "Đăng nhập", new_user_session_path, class:"nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Đăng xuất",  destroy_user_session_path , class:"nav-link", method: :delete%>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="#">Thông báo</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Liên hệ</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Ngôn ngữ
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Tiếng Anh</a>
              <a class="dropdown-item" href="#">Tiếng Việt</a>
              <a class="dropdown-item" href="#">Tiếng Nhật</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-12 col-xs-12">
      <div class="footHeader">
        <div class="navbar navbar-expand-sm">
          <a class="navbar-brand" href="/">
            <img src="http://cse.tlu.edu.vn/cse/assets/images/logo.jpg" class="d-inline-block align-top" alt="" loading="lazy">
          </a>
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link active" href="/"><i class="fa fa-home" aria-hidden="true"></i>Trang chủ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Giới thiệu</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Nghiên cứu khoa học</a>
            </li>
            <li class="nav-item">
              <%= link_to "Diễn đàn", wru_forum_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Tin tức</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header_admin.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="#">Home</a>
    </li>
    <li class="nav-item">
      <%= link_to "Manage Users", admin_users_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to "Manage Eventss", admin_events_path, class:"nav-link"%>
    </li>
  </ul>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
  </head>

  <body>
    <%= render  "layouts/header_admin" %>
    <div class="homePage">
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning"><%= alert %></div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render  "layouts/header" %>
    <div class="homePage">
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning"><%= alert %></div>
    <% end %>
      <%= yield %>
    </div>
    <%= render  "layouts/footer" %>
    <script>
      $(function(){
        createSticky($(".footHeader"));
      });
      function createSticky(sticky) {
        if (typeof sticky !== "undefined") {
          var	pos = sticky.offset().top,
            win = $(window);
            win.on("scroll", function() {
            win.scrollTop() >= pos ? sticky.addClass("fixed-top") : sticky.removeClass("fixed-top");      
          });			
        }
      }
    </script>
    <script>
      $(document).ready(function(){
        $('.counter').counterUp({
          delay: 100,
          time: 2000
        });
      });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js" integrity="sha512-kIRDPWIBoKpF79HJv3xBPQgZKjhxzqMGG2N68svvId45w9vp/hTXoR7cDERYhVEhLJTuSGb/c3+ZHgeQfLm0Hg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js" integrity="sha512-d8F1J2kyiRowBB/8/pAWsqUl0wSEOkG5KATkVV4slfblq9VRQ6MyDZVxWl2tWd+mPhuCbpTB4M7uU/x9FlgQ9Q==" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/layouts/forum/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-12">
      <div class="coverPhoto">
        <img src="https://scontent.fhan5-3.fna.fbcdn.net/v/t1.0-9/p720x720/89721928_2849363681796292_6475864247669620736_o.jpg?_nc_cat=106&ccb=2&_nc_sid=825194&_nc_ohc=hlJ_609u8qoAX-qA5rD&_nc_oc=AQmV1svjEX2mcYUazvk_ldF-25iwOj-kalwlEXGHjTsnQu2tre-9jdOImXLLqkGGWB4UlTvUIdmjhYLby5r6fWs6&_nc_ht=scontent.fhan5-3.fna&tp=6&oh=0e9509cfc7f4db9bbbc6e61264425c58&oe=5FC987B2">
      </div>
      <div class="ihqw7lf3 discj3wi l9j0dhe7">

      </div>
    </div>
    <div class="col-md-12">
      <div class="header">
        <nav class="navbar navbar-expand-sm publicBackground">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/wru/forum">Discussion</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Announements</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Rooms</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Members</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="/events">Events</a>
              </li>
            </ul>

            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
              <i class="fa fa-search"></i>Search
            </button>
            <div class="modal fade" id="myModal">
              <div class="modal-dialog">
                <div class="modal-content">
                  <!-- Modal Header -->
                  <div class="modal-header">
                    <h4 class="modal-title">Modal Heading</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                  <!-- Modal body -->
                  <div class="modal-body">
                    <form class="form-inline my-2 my-lg-0" action="/action_page.php">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text"><i class="fa fa-search"></i></span>
                        </div>
                        <input class="form-control mr-sm-2" type="text" placeholder="Search this group">
                        <button class="btn btn-primary" type="submit">Search</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
        </nav>
      </div>
    </div>
  </div>
</div>